### ISSUE TITLE
Sentence Doesn't Make Sense - Missing a Word?

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-resampling-methods#1]
"In contrast, the jackknife, the older of the two methods, works by taking samples by removing on, or more, observations at a time."

Is this sentence missing a word after 'on' ? Or is it a typo, and should say 'one' ? Unclear.

The sentence after this isn't much better: "Both aim estimate the variability of point estimators derived from the original samples." 

Should potentially be "Both aim **to** estimate the variability of point estimators derived from the original samples" although maybe don't use 'estimate' and 'point estimators' in the same sentence.

**Comment by fpolchow** [comment]
Thanks for flagging :) Fixed typos and added  more clarification.
