### ISSUE TITLE
3rd link listed is broken - 404 - on this page.

### ISSUE THREAD

**Issue by witchlane** [learn-co-curriculum/dsc-resampling-methods#2]
The third link listed under Additional Resources is broken.
![image](https://user-images.githubusercontent.com/44211854/63167199-8d04a100-bffe-11e9-8815-ee4f6f01fb2f.png)

![image](https://user-images.githubusercontent.com/44211854/63167228-a0177100-bffe-11e9-869c-16c98823bfbc.png)

**Comment by alexgriff** [comment]
Removed link
